# Generated by Django 3.2.7 on 2021-09-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/%d', verbose_name='Изображение')),
                ('stock', models.IntegerField(blank=True, default=0, verbose_name='В наличии (шт)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата контракта')),
                ('position', models.IntegerField(choices=[(0, 'Продавец'), (1, 'Старший продавец'), (2, 'Руководитель отдела продаж')], default=0, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма продажи')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', related_query_name='order', to='config.customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='config.product', verbose_name='Продукт')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', related_query_name='seller', to='config.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
